version: '2'
services:
  # rabbitmq-semnome017:
  #   container_name: rabbitmq-semnome017
  #   build: ./rabbitmq/
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # redis-semnome017:
  #   container_name: redis-semnome017
  #   build: ./redis/
  #   ports:
  #     - "6379:6379"

  mysql-semnome017:
    container_name: mysql-semnome017
    build:
      context: ./mysql
      dockerfile: Mysql.Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql123
      - MYSQL_DATABASE=semnome017