INSERT INTO semnome017.country (name) values ('Afghanistan');
INSERT INTO semnome017.country (name) values ('Albania');
INSERT INTO semnome017.country (name) values ('Algeria');
INSERT INTO semnome017.country (name) values ('Andorra');
INSERT INTO semnome017.country (name) values ('Angola');
INSERT INTO semnome017.country (name) values ('Antigua and Barbuda');
INSERT INTO semnome017.country (name) values ('Argentina');
INSERT INTO semnome017.country (name) values ('Armenia');
INSERT INTO semnome017.country (name) values ('Australia');
INSERT INTO semnome017.country (name) values ('Austria');
INSERT INTO semnome017.country (name) values ('Azerbaijan');
INSERT INTO semnome017.country (name) values ('Bahamas');
INSERT INTO semnome017.country (name) values ('Bahrain');
INSERT INTO semnome017.country (name) values ('Bangladesh');
INSERT INTO semnome017.country (name) values ('Barbados');
INSERT INTO semnome017.country (name) values ('Belarus');
INSERT INTO semnome017.country (name) values ('Belgium');
INSERT INTO semnome017.country (name) values ('Belize');
INSERT INTO semnome017.country (name) values ('Benin');
INSERT INTO semnome017.country (name) values ('Bhutan');
INSERT INTO semnome017.country (name) values ('Bolivia');
INSERT INTO semnome017.country (name) values ('Bosnia and Herzegovina');
INSERT INTO semnome017.country (name) values ('Botswana');
INSERT INTO semnome017.country (name) values ('Brazil');
INSERT INTO semnome017.country (name) values ('Brunei Darussalam');
INSERT INTO semnome017.country (name) values ('Bulgaria');
INSERT INTO semnome017.country (name) values ('Burkina Faso');
INSERT INTO semnome017.country (name) values ('Burundi');
INSERT INTO semnome017.country (name) values ('Cabo Verde');
INSERT INTO semnome017.country (name) values ('Cambodia');
INSERT INTO semnome017.country (name) values ('Cameroon');
INSERT INTO semnome017.country (name) values ('Canada');
INSERT INTO semnome017.country (name) values ('Central African Republic');
INSERT INTO semnome017.country (name) values ('Chad');
INSERT INTO semnome017.country (name) values ('Chile');
INSERT INTO semnome017.country (name) values ('China');
INSERT INTO semnome017.country (name) values ('Colombia');
INSERT INTO semnome017.country (name) values ('Comoros');
INSERT INTO semnome017.country (name) values ('Congo');
INSERT INTO semnome017.country (name) values ('Costa Rica');
INSERT INTO semnome017.country (name) values ('Côte d''Ivoire');
INSERT INTO semnome017.country (name) values ('Croatia');
INSERT INTO semnome017.country (name) values ('Cuba');
INSERT INTO semnome017.country (name) values ('Cyprus');
INSERT INTO semnome017.country (name) values ('Czech Republic');
INSERT INTO semnome017.country (name) values ('Democratic People''s Republic of Korea');
INSERT INTO semnome017.country (name) values ('Democratic Republic of the Congo');
INSERT INTO semnome017.country (name) values ('Denmark');
INSERT INTO semnome017.country (name) values ('Djibouti');
INSERT INTO semnome017.country (name) values ('Dominica');
INSERT INTO semnome017.country (name) values ('Dominican Republic');
INSERT INTO semnome017.country (name) values ('Ecuador');
INSERT INTO semnome017.country (name) values ('Egypt');
INSERT INTO semnome017.country (name) values ('El Salvador');
INSERT INTO semnome017.country (name) values ('Equatorial Guinea');
INSERT INTO semnome017.country (name) values ('Eritrea');
INSERT INTO semnome017.country (name) values ('Estonia');
INSERT INTO semnome017.country (name) values ('Eswatini');
INSERT INTO semnome017.country (name) values ('Ethiopia');
INSERT INTO semnome017.country (name) values ('Fiji');
INSERT INTO semnome017.country (name) values ('Finland');
INSERT INTO semnome017.country (name) values ('France');
INSERT INTO semnome017.country (name) values ('Gabon');
INSERT INTO semnome017.country (name) values ('Gambia');
INSERT INTO semnome017.country (name) values ('Georgia');
INSERT INTO semnome017.country (name) values ('Germany');
INSERT INTO semnome017.country (name) values ('Ghana');
INSERT INTO semnome017.country (name) values ('Greece');
INSERT INTO semnome017.country (name) values ('Grenada');
INSERT INTO semnome017.country (name) values ('Guatemala');
INSERT INTO semnome017.country (name) values ('Guinea');
INSERT INTO semnome017.country (name) values ('Guinea-Bissau');
INSERT INTO semnome017.country (name) values ('Guyana');
INSERT INTO semnome017.country (name) values ('Haiti');
INSERT INTO semnome017.country (name) values ('Honduras');
INSERT INTO semnome017.country (name) values ('Hungary');
INSERT INTO semnome017.country (name) values ('Iceland');
INSERT INTO semnome017.country (name) values ('India');
INSERT INTO semnome017.country (name) values ('Indonesia');
INSERT INTO semnome017.country (name) values ('Iran (Islamic Republic of)');
INSERT INTO semnome017.country (name) values ('Iraq');
INSERT INTO semnome017.country (name) values ('Ireland');
INSERT INTO semnome017.country (name) values ('Israel');
INSERT INTO semnome017.country (name) values ('Italy');
INSERT INTO semnome017.country (name) values ('Jamaica');
INSERT INTO semnome017.country (name) values ('Japan');
INSERT INTO semnome017.country (name) values ('Jordan');
INSERT INTO semnome017.country (name) values ('Kazakhstan');
INSERT INTO semnome017.country (name) values ('Kenya');
INSERT INTO semnome017.country (name) values ('Kiribati');
INSERT INTO semnome017.country (name) values ('Kuwait');
INSERT INTO semnome017.country (name) values ('Kyrgyzstan');
INSERT INTO semnome017.country (name) values ('Lao People''s Democratic Republic');
INSERT INTO semnome017.country (name) values ('Latvia');
INSERT INTO semnome017.country (name) values ('Lebanon');
INSERT INTO semnome017.country (name) values ('Lesotho');
INSERT INTO semnome017.country (name) values ('Liberia');
INSERT INTO semnome017.country (name) values ('Libya');
INSERT INTO semnome017.country (name) values ('Liechtenstein');
INSERT INTO semnome017.country (name) values ('Lithuania');
INSERT INTO semnome017.country (name) values ('Luxembourg');
INSERT INTO semnome017.country (name) values ('Madagascar');
INSERT INTO semnome017.country (name) values ('Malawi');
INSERT INTO semnome017.country (name) values ('Malaysia');
INSERT INTO semnome017.country (name) values ('Maldives');
INSERT INTO semnome017.country (name) values ('Mali');
INSERT INTO semnome017.country (name) values ('Malta');
INSERT INTO semnome017.country (name) values ('Marshall Islands');
INSERT INTO semnome017.country (name) values ('Mauritania');
INSERT INTO semnome017.country (name) values ('Mauritius');
INSERT INTO semnome017.country (name) values ('Mexico');
INSERT INTO semnome017.country (name) values ('Micronesia (Federated States of)');
INSERT INTO semnome017.country (name) values ('Monaco');
INSERT INTO semnome017.country (name) values ('Mongolia');
INSERT INTO semnome017.country (name) values ('Montenegro');
INSERT INTO semnome017.country (name) values ('Morocco');
INSERT INTO semnome017.country (name) values ('Mozambique');
INSERT INTO semnome017.country (name) values ('Myanmar');
INSERT INTO semnome017.country (name) values ('Namibia');
INSERT INTO semnome017.country (name) values ('Nauru');
INSERT INTO semnome017.country (name) values ('Nepal');
INSERT INTO semnome017.country (name) values ('Netherlands');
INSERT INTO semnome017.country (name) values ('New Zealand');
INSERT INTO semnome017.country (name) values ('Nicaragua');
INSERT INTO semnome017.country (name) values ('Niger');
INSERT INTO semnome017.country (name) values ('Nigeria');
INSERT INTO semnome017.country (name) values ('North Macedonia');
INSERT INTO semnome017.country (name) values ('Norway');
INSERT INTO semnome017.country (name) values ('Oman');
INSERT INTO semnome017.country (name) values ('Pakistan');
INSERT INTO semnome017.country (name) values ('Palau');
INSERT INTO semnome017.country (name) values ('Panama');
INSERT INTO semnome017.country (name) values ('Papua New Guinea');
INSERT INTO semnome017.country (name) values ('Paraguay');
INSERT INTO semnome017.country (name) values ('Peru');
INSERT INTO semnome017.country (name) values ('Philippines');
INSERT INTO semnome017.country (name) values ('Poland');
INSERT INTO semnome017.country (name) values ('Portugal');
INSERT INTO semnome017.country (name) values ('Qatar');
INSERT INTO semnome017.country (name) values ('Republic of Korea');
INSERT INTO semnome017.country (name) values ('Republic of Moldova');
INSERT INTO semnome017.country (name) values ('Romania');
INSERT INTO semnome017.country (name) values ('Russian Federation');
INSERT INTO semnome017.country (name) values ('Rwanda');
INSERT INTO semnome017.country (name) values ('St. Kitts and Nevis');
INSERT INTO semnome017.country (name) values ('St. Lucia');
INSERT INTO semnome017.country (name) values ('St. Vincent and the Grenadines');
INSERT INTO semnome017.country (name) values ('Samoa');
INSERT INTO semnome017.country (name) values ('San Marino');
INSERT INTO semnome017.country (name) values ('São Tomé and Príncipe');
INSERT INTO semnome017.country (name) values ('Saudi Arabia');
INSERT INTO semnome017.country (name) values ('Senegal');
INSERT INTO semnome017.country (name) values ('Serbia');
INSERT INTO semnome017.country (name) values ('Seychelles');
INSERT INTO semnome017.country (name) values ('Sierra Leone');
INSERT INTO semnome017.country (name) values ('Singapore');
INSERT INTO semnome017.country (name) values ('Slovakia');
INSERT INTO semnome017.country (name) values ('Slovenia');
INSERT INTO semnome017.country (name) values ('Solomon Islands');
INSERT INTO semnome017.country (name) values ('Somalia');
INSERT INTO semnome017.country (name) values ('South Africa');
INSERT INTO semnome017.country (name) values ('South Sudan');
INSERT INTO semnome017.country (name) values ('Spain');
INSERT INTO semnome017.country (name) values ('Sri Lanka');
INSERT INTO semnome017.country (name) values ('Sudan');
INSERT INTO semnome017.country (name) values ('Suriname');
INSERT INTO semnome017.country (name) values ('Sweden');
INSERT INTO semnome017.country (name) values ('Switzerland');
INSERT INTO semnome017.country (name) values ('Syrian Arab Republic');
INSERT INTO semnome017.country (name) values ('Tajikistan');
INSERT INTO semnome017.country (name) values ('Thailand');
INSERT INTO semnome017.country (name) values ('Timor-Leste');
INSERT INTO semnome017.country (name) values ('Togo');
INSERT INTO semnome017.country (name) values ('Tonga');
INSERT INTO semnome017.country (name) values ('Trinidad and Tobago');
INSERT INTO semnome017.country (name) values ('Tunisia');
INSERT INTO semnome017.country (name) values ('Turkey');
INSERT INTO semnome017.country (name) values ('Turkmenistan');
INSERT INTO semnome017.country (name) values ('Tuvalu');
INSERT INTO semnome017.country (name) values ('Uganda');
INSERT INTO semnome017.country (name) values ('Ukraine');
INSERT INTO semnome017.country (name) values ('United Arab Emirates');
INSERT INTO semnome017.country (name) values ('United Kingdom of Great Britain and Northern Ireland');
INSERT INTO semnome017.country (name) values ('United Republic of Tanzania');
INSERT INTO semnome017.country (name) values ('United States of America');
INSERT INTO semnome017.country (name) values ('Uruguay');
INSERT INTO semnome017.country (name) values ('Uzbekistan');
INSERT INTO semnome017.country (name) values ('Vanuatu');
INSERT INTO semnome017.country (name) values ('Venezuela (Bolivarian Republic of)');
INSERT INTO semnome017.country (name) values ('Viet Nam');
INSERT INTO semnome017.country (name) values ('Yemen');
INSERT INTO semnome017.country (name) values ('Zambia');
INSERT INTO semnome017.country (name) values ('Zimbabwe');
